//------------------------------------------------------------------------------
// This code provides additional routine for KinectFusionExplorer-D2D.
// It supports loav/save of TSDF volume generated by KinectFusion.
// Author: Seung-Tak Noh (seungtak.noh@gmail.com)
//------------------------------------------------------------------------------
#pragma once

#include <vector>
#include "NuiKinectFusionApi.h"

/// <summary>
/// data format for TSDF volume save/load
/// </summary>
struct KinfuData
{
	Matrix4 worldToCameraTransform;
	Matrix4 worldToVolumeTransform;

	NUI_FUSION_RECONSTRUCTION_PARAMETERS reconsParams;
	std::vector<short> volumeBlock;
	std::vector<int> colorVolumeBlock;
};

/// <summary>
/// import volumetric data in XML formatted file
/// </summary>
bool LoadXML(const char* xmlFile, KinfuData& kinfuData);

/// <summary>
/// export volumetric data in XML formatted file
/// </summary>
bool SaveXML(const char* xmlFile, const KinfuData& kinfuData);
