//------------------------------------------------------------------------------
// This code provides additional routine for KinectFusionExplorer-D2D.
// It supports loav/save of TSDF volume generated by KinectFusion.
// Author: Seung-Tak Noh (seungtak.noh@gmail.com)
//------------------------------------------------------------------------------
#pragma once

#include <vector>
#include "NuiKinectFusionApi.h"
#include <glm/glm.hpp>

/// <summary>
/// Simple coordinate conversion from Kinect-CV coordinate (right, down, forward, right-handed)
/// to OpenGL coordinate (right, up, backward, right-handed)
/// </summary>
Matrix4 ConvertGL2Kinect(const glm::mat4& matGL);

/// <summary>
/// Simple coordinate conversion from OpenGL coordinate (right, up, backward, right-handed)
/// to Kinect-CV coordinate (right, down, forward, right-handed)
/// </summary>
glm::mat4 ConvertKinect2GL(const Matrix4& mat);

/// <summary>
/// data format for TSDF volume save/load
/// </summary>
struct KinfuData
{
	Matrix4 worldToCameraTransform;
	Matrix4 worldToVolumeTransform;

	NUI_FUSION_RECONSTRUCTION_PARAMETERS reconsParams;
	std::vector<short> volumeBlock;
	std::vector<int> colorVolumeBlock;
};

/// <summary>
/// import volumetric data in XML formatted file
/// </summary>
bool LoadXML(const char* xmlFile, KinfuData& kinfuData);

/// <summary>
/// export volumetric data in XML formatted file
/// </summary>
bool SaveXML(const char* xmlFile, const KinfuData& kinfuData);
